---
title: "Metabolite analysis"
output: html_notebook
---

```{r}
library(ggpubr)
```


```{r}
#normality check#

#GlycA and B
ggqqplot(metadata_ht2$GlycA)
ggdensity(metadata_ht2$GlycA)

ggqqplot(metadata_ht2$GlycB)
ggdensity(metadata_ht2$GlycB)

plot(metadata_ht2$GlycA, metadata_ht2$GlycB)
```


```{r}
#correlation test#
cor.test(metadata_ht2$GlycA, metadata_ht2$GlycB, method="pearson")
```


```{r}
#normality check#
ggqqplot(metadata_ht2$SPC1)
ggdensity(metadata_ht2$SPC1)

ggqqplot(log(metadata_ht2$SPC1))
ggdensity(log(metadata_ht2$SPC1))


#SPC
ggqqplot(metadata_ht2$SPC2)
ggdensity(metadata_ht2$SPC2)

ggqqplot(log(metadata_ht2$SPC2))
ggdensity(log(metadata_ht2$SPC2))

ggqqplot(metadata_ht2$SPC2)
ggdensity(metadata_ht2$SPC3)

ggqqplot(log(metadata_ht2$SPC3))
ggdensity(log(metadata_ht2$SPC3))


plot(log(metadata_ht2$SPC1), log(metadata_ht2$SPC2))
plot(log(metadata_ht2$SPC1), log(metadata_ht2$SPC3))
plot(log(metadata_ht2$SPC2), log(metadata_ht2$SPC3))
```


```{r}
#correlation test#
cor.test(log(metadata_ht2$SPC1), log(metadata_ht2$SPC2), method="pearson")

cor.test(log(metadata_ht2$SPC2), log(metadata_ht2$SPC3), method="pearson")

cor.test(log(metadata_ht2$SPC1), log(metadata_ht2$SPC3), method="pearson")
```


