---
title: "Venn Diagram of DMPs script"
output: html_notebook
---

```{r}
library("limma")
```


```{r}
design <- model.matrix(~GlycA + 
                        as.factor(BioMood.group) +
                        PC1+
                        PC2+
                        PC3+
                        PC4,
                       metadata_ht2)

design <- model.matrix(~GlycB + 
                        as.factor(BioMood.group) +
                        PC1+
                        PC2+
                        PC3+
                        PC4,
                       metadata_ht2)

#fit M vals and contrast
M.fit <- eBayes(lmFit(M, design))

##Deciding significance based on p value < 5e-5

GlycA_results <- decideTests(M.fit, adjust.method = "none", p.value = 0.00005)

GlycB_results <- decideTests(M.fit, adjust.method = "none", p.value = 0.00005)


GlycA <- GlycA_results[,which(colnames(GlycA_results) == "GlycA")]

GlycB <- GlycB_results[,which(colnames(GlycB_results) == "GlycB")]


# Merging GlycA and GlycB results
Glyc_merged_data <- merge(GlycA, GlycB, by = "row.names")
# Set row names back to the merged row names and drop the created 'Row.names' column
rownames(Glyc_merged_data) <- Glyc_merged_data$Row.names
Glyc_merged_data <- Glyc_merged_data[, -1]

save(Glyc_merged_data, file = file.path(resdir, "Glyc_data_venndiagram"))

data <- vennCounts(Glyc_merged_data)

vennDiagram(data, 
    include=c("up", "down"),
    counts.col=c("black", "black"),
    circle.col = c("red", "blue","green3"))

pdf(file=paste0(outdir,sep="/","plots/Glyc_VennDiagram.pdf"))

dev.off()

```

```{r}
design <- model.matrix(~SPC1 + 
                        as.factor(BioMood.group) +
                        PC1+
                        PC2+
                        PC3+
                        PC4,
                       metadata_ht2)

design <- model.matrix(~SPC2 + 
                        as.factor(BioMood.group) +
                        PC1+
                        PC2+
                        PC3+
                        PC4,
                       metadata_ht2)

design <- model.matrix(~SPC3 + 
                        as.factor(BioMood.group) +
                        PC1+
                        PC2+
                        PC3+
                        PC4,
                       metadata_ht2)

#fit M vals and contrast
M.fit <- eBayes(lmFit(M, design))

SPC1_results <- decideTests(M.fit, adjust.method = "none", p.value = 0.00005)

SPC2_results <- decideTests(M.fit, adjust.method = "none", p.value = 0.00005)

SPC3_results <- decideTests(M.fit, adjust.method = "none", p.value = 0.00005)


SPC1 <- SPC1_results[,which(colnames(SPC1_results) == "SPC1")]

SPC2 <- SPC2_results[,which(colnames(SPC2_results) == "SPC2")]

SPC3 <- SPC3_results[,which(colnames(SPC3_results) == "SPC3")]

# Merging SPC1 and SPC2
merged_12 <- merge(SPC1, SPC2, by = "row.names")
rownames(merged_12) <- merged_12$Row.names
merged_12 <- merged_12[, -1]

# Merging with SPC3
SPCmerged_data <- merge(merged_12, SPC3, by = "row.names")
rownames(SPCmerged_data) <- SPCmerged_data$Row.names
SPCmerged_data <- SPCmerged_data[, -1]

save(SPCmerged_data, file = file.path(resdir, "SPC_data_venndiagram"))

data <- vennCounts(SPCmerged_data)

vennDiagram(data, 
    include=c("up", "down"),
    counts.col=c("black", "black"),
    circle.col = c("red", "blue","green3"))

pdf(file=paste0(outdir,sep="/","plots/SPC_VennDiagram.pdf"))

```

```{r}
sessionInfo()
```



